# Generated by Django 5.0.3 on 2024-03-18 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Create',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_name', models.CharField(max_length=20)),
                ('pro_price', models.IntegerField()),
                ('pro_quantity', models.IntegerField()),
                ('purchase_date', models.DateField()),
            ],
        ),
    ]
